name: Daily Run

on:
  schedule:
  - cron: "10 15 * * *"
  workflow_dispatch:

env:
  GOAMD64: v3

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18.3

    - name: Run
      run: go run ./main.go run -j ${{ secrets.BILIJCT }} -d ${{ secrets.DEDEUSERID }} -m ${{ secrets.DEDEUSERID_CKMD5 }} -s ${{ secrets.SESSDATA }}
